// index.js
module.exports = {
  Assessment: require('./Assessment'),
  AuditLog: require('./AuditLog'),
  Calendar: require('./Calendar'),
  Certificate: require('./Certificate'),
  Course: require('./Course'),
  Exam: require('./Exam'),
  Instructor: require('./Instructor'),
  Lesson: require('./Lesson'),
  Notification: require('./Notification'),
  Report: require('./Report'),
  Student: require('./Student'),
  Submission: require('./Submission'),
  SuperAdmin: require('./SuperAdmin'),
  Unit: require('./Unit'),
  Quiz: require('./Quiz'),
  Marks: require('./Marks'),
  Assignment: require('./Assignment'),
  SubmissionAssignment: require('./SubmissionAssignment'),
  Discussion: require('./Discussion'),
  OnlineSession: require('./onlineSession'),
};

module.exports = {
  Assessment,
  AuditLog,
  Calendar,
  Certificate,
  Course,
  Exam,
  Instructor,
  Lesson,
  Notification,
  Report,
  Student,
  Submission,
  SuperAdmin,
  Unit,
  Quiz,
  Marks,
  Assignment,
  SubmissionAssignment,
  Discussion,
  OnlineSession
};